services:
  - type: web
    name: painel-expedicao-laqualite
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ENABLE_KDS
        value: "true"
      - key: SYNC_OPEN_ORDERS_INTERVAL_MS
        value: "10000"
